spring:
  application:
    name: edging-service
zuul:
  routes:
    running-location-service:
      path: /running-location-service/**
      url: http://localhost:9000
    supply-location-service:
      path: /supply-location-service/**
      url: http://localhost:9001